name: 1-Simple Matrix

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 18]

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Run code
        run: node -e "fetch('https://example.com').then(res => res.text()).then(console.log)"
